### ISSUE TITLE
Java 8 Error 

### ISSUE THREAD

**Issue by FitApps7** [defano/jmonet#23]
To add its dependency you should use java 8, for this min SDK is 26 
To check after sync gradle rebuild your project, you will see it

Error:com.android.builder.dexing.DexArchiveBuilderException: Failed to process C:\Users\Ahsan\.gradle\caches\modules-2\files-2.1\com.defano.jmonet\jmonet\0.2.2\a92b9db3d14092f0a4062560fa1a63516e1b5345\jmonet-0.2.2.jar
Error:com.android.builder.dexing.DexArchiveBuilderException: Error while dexing com/defano/jmonet/tools/TextTool.class
Error:com.android.dx.cf.code.SimException: invalid opcode ba (invokedynamic requires --min-sdk-version >= 26)
Error:Execution failed for task ':app:transformClassesWithDexBuilderForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.dexing.DexArchiveBuilderException: com.android.builder.dexing.DexArchiveBuilderException: Failed to process C:\Users\Ahsan\.gradle\caches\modules-2\files-2.1\com.defano.jmonet\jmonet\0.2.2\a92b9db3d14092f0a4062560fa1a63516e1b5345\jmonet-0.2.2.jar
Information:BUILD FAILED in 13s
Information:4 errors

**Comment by defano** [comment]
Hi FitApps7,

It appears that you're trying to use this library in an Android application. Unfortunately, this was designed for Java Swing and JavaFX-based (desktop) application. It makes use of a variety of Java packages that are not available on Android and will therefore not work in mobile apps.

Let me know if I've misunderstood what you're trying to do--

**Comment by FitApps7** [comment]
So how I can get like this on android?
Lasso tool, magic wand tool etc.

**Comment by defano** [comment]
You might try one of the libraries here: https://android-arsenal.com/tag/185.

**Comment by FitApps7** [comment]
thanks
