### ISSUE TITLE
JavaFX cannot change pencil color

### ISSUE THREAD

**Issue by duongxinh2003** [defano/jmonet#39]
I use javafx to create canvas with image background but when I drawing on this with color picker, the line is default white color. Without image background, I can change color normally.
![image](https://user-images.githubusercontent.com/25058528/77985484-d19b3d80-733e-11ea-80ee-3a319fd09580.png)
![image](https://user-images.githubusercontent.com/25058528/77985531-f8f20a80-733e-11ea-9cb9-f4ce3b43e751.png)

**Comment by defano** [comment]
This is the intended behavior. The pencil tool acts as an eraser if you start your path on a non-empty (fully transparent) pixel. It draws color otherwise.

Try using the PaintbrushTool with a single-pixel brush to achieve the effect you're looking for.

**Comment by duongxinh2003** [comment]
Thank you, I solved this issue. Here is my code `        pencil = PaintToolBuilder.create(PaintToolType.PAINTBRUSH)
                .withStroke(StrokeBuilder.withShape().ofCircle(15).build())
                .withStrokePaint(new Color((float) cpColor.getValue().getRed(), (float) cpColor.getValue().getGreen(), (float) cpColor.getValue().getBlue()))
                .makeActiveOnCanvas(canvas)
                .build();`
