### ISSUE TITLE
How to select or remove Rectangle or Oval or Line?

### ISSUE THREAD

**Issue by winthesky** [defano/jmonet#42]
How to select or remove Rectangle or Oval or Line ?

**Comment by defano** [comment]
Hi @winthesky ,

Totally missed this--sorry for the delayed response.

As you've likely already discovered, you cannot select or remove a shape directly (as you might be accustomed to with a diagramming/draw tool like Visio). 

JMonet is a raster graphics editor which operates at the bitmap level. You can select and "erase" a _region_ of paint; you can use the eraser tool to change pixels back into their original transparent state; or you can use the undo function to remove recent changes. But you cannot select or edit individual shapes.

Hope this helps--

Matt
